apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storage.alpha.openshift.io/access-mode: ReadWriteOnce
    storageclass.kubernetes.io/is-default-class: 'true'
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
parameters:
  encrypted: 'true'
  type: gp2
  zone: eu-west-1a
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: Immediate
