apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  labels:
    app: ghostis
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
spec:
  clusterIP: 172.30.180.59
  ports:
    - name: 2368-tcp
      port: 443
      protocol: TCP
      targetPort: 2368
  selector:
    deploymentconfig: ghostis
  sessionAffinity: None
  type: ClusterIP
